# Files to protect (used by tamper_protection.py)
protected_files:
  - config/auth.yml

# Directories/files to monitor (used by file_watcher.py)
monitored_paths:
  - /home/mechanic/test

white_list_files:
  - /var/log/lightdm
  - /etc/resolv.conf